name: Fetch newest BeatMods mods

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '30 5,17 * * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node main
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: Port the newest BeatMods mods to lithium format.
    
    
